game-settings:
  min-players: 2
  max-players: 12
  starting-time: 30
  finishing-time: 5
  sounds:
    player-loss-game: CAT_HIT
    player-pass-game: LEVELUP
    player-death: EXPLODE
    arena-starting: CLICK
    arena-countdown: NOTE_PLING
    arena-start: ORB_PICKUP
  # For 1.13+
  # sounds:
  #    player-loss-game: ENTITY_CAT_HURT
  #    player-pass-game: ENTITY_PLAYER_LEVELUP
  #    player-death: ENTITY_GENERIC_EXPLODE
  #    arena-starting: UI_BUTTON_CLICK
  #    arena-countdown: BLOCK_NOTE_BLOCK_PLING
  #    arena-start: ENTITY_EXPERIENCE_ORB_PICKUP
  game-time:
    "1": 60
    "7": 600

lobby:
  world: ""
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0