name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
api-version: 1.13
api: 1.13
depend:
  - "PlaceholderAPI"
softdepend:
  - "SwiftBoard"
url: ${url}
commands:
  squidgame:
    aliases: ["sg", "sq", "squid"]
    description: "This is an example plugin."