name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
commands:
  squidgame:
    aliases: ["sg", "sq", "squid"]
    description: "This is an example plugin."